### ISSUE TITLE
Path escaping on Windows

### ISSUE THREAD

**Issue by teamplayer3** [eopb/cargo-override#132]
In `fn toml::source` if `manifest_directory != working_dir` is true, the resulting `path` gets transformed and escaped in windows. After this, the toml parse test fails.

- Input Path: /path/to/manifest
- Output Path C:\\\path\\\to\\\manifest

Not tested it with the tool itself. Discovered it while testing the function `patch_manifest`.

**Comment by teamplayer3** [comment]
Related to #87

**Comment by eopb** [comment]
Thanks for pointing this one out. As you mentioned, this increases the priority for solving https://github.com/eopb/cargo-override/issues/87

Windows support is completely untested because I don't have access to a windows machine. I had to make a [number of fixes](https://github.com/eopb/cargo-override/pull/79) to get tests to pass on MacOS. Since I made those change, I was recently able to enable automated testing on MacOS in CI https://github.com/eopb/cargo-override/pull/123. It would be great to make similar changes for windows to ensure that compatibility is maintained

**Comment by eopb** [comment]
I've fixed the path escaping issue in https://github.com/eopb/cargo-override/pull/134.

I've also done some work to ensure that the tests can be run on windows in #144 and #140

I'm going to close this issue, but do let me know if there are still issues on Windows. I was only able to test my changes with a GitHub actions windows image, not a real machine, so it's very possible I've missed something.

Thanks again for raising the issue :raised_hands:
